- client/src/components/AdminMenu.js
- client/src/components/AdminMenu.test.js
- client/src/components/Footer.test.js
- client/src/components/Header.test.js
- client/src/components/Prices.js
- client/src/components/Prices.test.js
- client/src/components/UserMenu.test.js
- jest.frontend.config.js
- package-lock.json
- package.json
- Uncomment link to users page in `AdminMenu`
- Add jest-dom package for testing
- Change id of last item in `Prices` to unique (5)
> Create unit tests for components

- middlewares/authMiddleware.test.js
> Create unit tests for authMiddleware

- models/productModel.test.js
- package-lock.json
- package.json
Mockingoose is used for mocking Mongoose models.
> test: Add Unit Tests for Mongoose Product Model

- client/src/context/auth.js
- client/src/context/auth.test.js
- client/src/context/cart.js
- client/src/context/cart.test.js
- client/src/context/search.js
- client/src/context/search.test.js
---
auth
- Use functional update for `setAuth` to exclude `auth` from the `useEffect` dependency array
> Add unit tests for frontend hooks

- client/src/pages/Search.js
- client/src/pages/Search.test.js
---
- Add `key` prop to each search result child in the list
- Replace `class` with `className` for the two buttons
> Add unit tests for Search page

- client/src/pages/admin/AdminOrders.js
- jest.backend.config.js
- models/orderModel.js
- models/orderModel.test.js
- package-lock.json
- package.json
Add tests to verify CRUD operations on orderModel.js
Correct spelling of enums under status in orderModel.js and AdminOrders.js
Add coverage of models in jest.backend.config.js
> Add tests for orderModel.js

- client/package-lock.json
- client/package.json
- client/src/pages/About.test.js
- client/src/pages/CartPage.js
- client/src/pages/CartPage.test.js
- client/src/pages/Categories.js
- client/src/pages/Categories.test.js
- client/src/pages/CategoryProduct.js
- client/src/pages/CategoryProduct.test.js
- client/src/pages/Contact.test.js
- client/src/pages/Pagenotfound.test.js
- client/src/pages/Policy.test.js
- client/src/pages/ProductDetails.js
- client/src/pages/ProductDetails.test.js
**Bug fixes**
1. install react-icon package for `Contact.js`
> Create Unit tests for Common Pages

- config/db.js
- config/db.test.js
> Add unit tests for db connectDB

- client/src/components/Form/CategoryForm.test.js
- client/src/components/Form/SearchInput.test.js
- client/src/pages/HomePage.js
- client/src/pages/HomePage.test.js
The Home Page is currently not being covered by any unit tests. Let's implement some unit tests to cover the code and bump up code coverage.
> test: Implement Home Page Unit Tests

- client/src/pages/Search.js
- client/src/pages/Search.test.js
- Add functionalities to button in search page: 'More Details' and 'Add to Cart'
- Add tests for navigate and add to cart
> Fix search buttons and add tests

- helpers/authHelper.js
- helpers/authHelper.test.js
> Create unit tests for authHelper

- models/userModel.js
- models/userModel.test.js
> Add tests for userModel

- client/src/pages/admin/Users.js
- client/src/pages/admin/Users.test.js
---
```js
import { getUsersController } from "./authController.js";
import userModel from "../models/userModel.js";
jest.mock("../models/userModel.js");
const mockResponse = () => {
const res = {};
res.status = jest.fn().mockReturnValue(res);
res.send = jest.fn().mockReturnValue(res);
return res;
};
describe("getUsersController", () => {
afterEach(() => {
jest.clearAllMocks();
});
it("should return all users with role 0", async () => {
const mockUsers = [
{ _id: "1", name: "John Doe", email: "john@example.com", role: 0 },
{ _id: "2", name: "Jane Doe", email: "jane@example.com", role: 0 },
{ _id: "3", name: "Admin", email: "admin@example.com", role: 1 },
];
userModel.find.mockImplementation((query) =>
mockUsers.filter((user) => user.role === query.role)
);
const req = {};
const res = …
```
> Update users page unit tests

- client/src/pages/Auth/Register.js
- client/src/pages/Auth/Register.test.js
made minor logic changes to js instead of html
added field validation tests
added routing validation
> Add more tests for register page

- client/src/tests/integration-test/CreateProduct.integration.test.jsx
- jest.frontend.config.js
- package.json
Removed all mocks except for axios and antd.
> Add CreateProduct integration tests

- client/src/tests/integration-test/CreateCategory.integration.test.jsx
Removed all mocks except for axios.
> Add CreateCategory integration tests

- client/src/hooks/useCategory.js
- client/src/tests/integration-test/CreateProduct.integration.test.jsx
- client/src/tests/integration-test/UpdateProduct.integration.test.jsx
Removed all mocks except for axios and antd.
> Add UpdateProduct integration tests

- client/src/tests/integration-test/AdminOrders.integration.test.jsx
Removed all mocks except for axios and antd.
> Add AdminOrders integration tests

- client/src/pages/admin/CreateCategory.js
- client/src/pages/admin/CreateProduct.js
- client/src/pages/admin/Users.js
- client/src/pages/user/Dashboard.js
- client/src/pages/user/Orders.js
- client/src/pages/user/Profile.js
Previously there was a slight overflow in certain pages due to additional margins, resulting in additional right white spaces
> [UI Fix] Fix Overflowing Pages

- client/src/pages/user/Profile.js
- client/src/pages/user/Profile.test.js
- controllers/authController.js
- controllers/authController.test.js
- ui-tests/user-update-profile.spec.js
**FIXES**
- add validation check for update profile to ensure non-empty fields -> fix unit tests for profile 
- fix accuracy of error message of password minimum length
> [UI Test] User Update Profile Flow

- client/src/integration-tests/pages/admin/AdminDashboard.integration.test.jsx
> Add integration tests for AdminDashboard

- controllers/categoryController.js
- controllers/categoryController.test.js
- Add error states when adding/ updated category to same name
> Add error when non-unique category names are added or edited

- controllers/categoryController.js
- controllers/categoryController.test.js
- tests/integration-test/categoryController.integration.test.js
> Add categoryController integration tests

- tests/integration-test/categoryModel.integration.test.js
> Add categoryModel integration test

- client/src/integration-tests/pages/Categories.integration.test.jsx
> Add category page integration tests

- routes/productRoutes.js
- tests/integration-test/authHelper.integration.test.js
- tests/integration-test/authMiddleware.integration.test.js
**fixes**
- added isadmin and requiresignin middlewares for delete product
> authMiddleware and authHelper integration tests

- ui-tests/admin-view-users.spec.js
- ui-tests/user-update-profile.spec.js
> UI test fixes

- client/src/pages/HomePage.js
- client/src/pages/HomePage.test.js
- controllers/productController.js
- controllers/productController.test.js
- routes/productRoutes.js
Fixes behavior of filter on homepage by introducing query params to the product-list endpoint.
> Update filters on homepage
